# Generated by Django 5.1.4 on 2024-12-14 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoAlimento', models.CharField(max_length=50)),
                ('cantidad', models.CharField(max_length=50)),
                ('frecuencia', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=50)),
                ('peso', models.FloatField()),
                ('especie', models.CharField(max_length=50)),
                ('historialSalud', models.CharField(max_length=50)),
                ('tipoColumnaVertebral', models.CharField(choices=[('Vertebrado', 'Vertebrado'), ('Invertebrado', 'Invertebrado')], max_length=15)),
                ('tipoAlimentacion', models.CharField(choices=[('Carnivoro', 'Carnivoro'), ('Herbivoro', 'Herbivoro'), ('Omnivoro', 'Omnivoro')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField()),
                ('cedula', models.CharField(max_length=10)),
                ('numeroTelefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintoma', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Exhibicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('tema', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoHabitat', models.CharField(max_length=100)),
                ('temperatura', models.FloatField()),
                ('area', models.FloatField()),
                ('capacidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('diagnostico', models.CharField(max_length=100)),
                ('veterinario', models.CharField(max_length=100)),
                ('tratamiento', models.CharField(max_length=100)),
                ('anamnesis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jaula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('Ocupada', 'Ocupada'), ('Mantenimiento', 'Mantenimiento'), ('Desocupada', 'Desocupada'), ('Reservada', 'Reservada')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PanelInformativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCientifico', models.CharField(max_length=50)),
                ('nombreComun', models.CharField(max_length=50)),
                ('familia', models.CharField(max_length=50)),
                ('habitatNatural', models.CharField(max_length=50)),
                ('dieta', models.CharField(max_length=50)),
                ('estadoDeConservacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipoZona', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='zoologico.persona')),
                ('cargo', models.CharField(max_length=20)),
                ('horario', models.CharField(max_length=20)),
                ('sueldo', models.FloatField()),
            ],
            bases=('zoologico.persona',),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='zoologico.persona')),
                ('boleto', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='zoologico.boleto')),
            ],
            bases=('zoologico.persona',),
        ),
        migrations.CreateModel(
            name='Conserje',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='zoologico.empleado')),
                ('areaLimpieza', models.CharField(max_length=50)),
            ],
            bases=('zoologico.empleado',),
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='zoologico.empleado')),
                ('areaResponsable', models.CharField(max_length=50)),
            ],
            bases=('zoologico.empleado',),
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='zoologico.empleado')),
                ('especialidad', models.CharField(max_length=50)),
                ('animalCargo', models.CharField(max_length=50)),
            ],
            bases=('zoologico.empleado',),
        ),
        migrations.CreateModel(
            name='Zoologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('horarioAtencion', models.CharField(max_length=100)),
                ('zona', models.ManyToManyField(related_name='zonas', to='zoologico.zona')),
                ('empleado', models.ManyToManyField(default=0, related_name='empleados', to='zoologico.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='zoologico.empleado')),
                ('especialidad', models.CharField(max_length=50)),
                ('idioma', models.CharField(max_length=50)),
                ('turno', models.CharField(max_length=50)),
                ('boleto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos_guia', to='zoologico.boleto')),
            ],
            bases=('zoologico.empleado',),
        ),
        migrations.CreateModel(
            name='Taquillero',
            fields=[
                ('empleado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='zoologico.empleado')),
                ('boleto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos_taquillero', to='zoologico.boleto')),
            ],
            bases=('zoologico.empleado',),
        ),
    ]
